import Typography from '@mui/material/Typography'
import type { NextPage } from 'next'
import Head from 'next/head'
import StudentList from '../components/StudentList'
import { Student } from './api/db'

type Props = {
  students: Student[]
}

const InProcess: NextPage<Props> = ({ students }) => {
  return (
    <>
      <Head>
        <title>In Process</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Typography variant='h1'>
        Estudiantes
        <Typography
          variant="overline"
          sx={{
            marginLeft: 2,
          }}
        >
          en proceso
        </Typography>
      </Typography>
      <StudentList students={students} />
    </>
  )
}

export const getServerSideProps = async () => {
  const res = await fetch('http://localhost:3000/api/inprocess')
  const students = await res.json()

  return {
    props: { students }
  }
}

export default InProcess
